apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: jitsi
    k8s-app-component: jigasi
  name: jitsi-jigasi
  namespace: jitsi
spec:
  replicas: 1
#  strategy:
#    type: Recreate
  serviceName: jitsi-jigasi
  selector:
    matchLabels:
      k8s-app: jitsi
      k8s-app-component: jigasi
  template:
    metadata:
      labels:
        k8s-app: jitsi
        k8s-app-component: jigasi
    spec:
      containers:
        - name: jigasi
          image: jitsi/jigasi:stable-5870
          imagePullPolicy: IfNotPresent
          env:
          - name: XMPP_SERVER
            value: xmpp-1
          - name: XMPP_DOMAIN
            value: meet.jitsi
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.jitsi
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.meet.jitsi
          - name: XMPP_MUC_DOMAIN
            value: muc.meet.jitsi
          - name: JIGASI_XMPP_USER
            value: jigasi
          - name: JIGASI_XMPP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jitsi-config
                key: JIGASI_XMPP_PASSWORD
          - name: JIGASI_SIP_URI
            value: cclinax@sip2sip.info
          - name: JIGASI_SIP_PASSWORD
            value:
          - name: JIGASI_SIP_SERVER
            value:
          - name: JIGASI_SIP_PORT
            value: "5060"
          - name: JIGASI_SIP_TRANSPORT
            value: UDP
          - name: JIGASI_BREWERY_MUC
            value: jigasibrewery
          - name: JIGASI_PORT_MIN
            value: "30000"
          - name: JIGASI_PORT_MAX
            value: "30050"
          - name: JIGASI_ENABLE_SDES_SRTP
            value: "0"
          - name: JIGASI_SIP_KEEP_ALIVE_METHOD
            value: OPTIONS
          - name: JIGASI_HEALTH_CHECK_SIP_URI
            value: keepalive
          - name: JIGASI_HEALTH_CHECK_INTERVAL
            value: "300000"
          - name: ENABLE_TRANSCRIPTIONS
            value: "0"
          - name: JIGASI_TRANSCRIBER_RECORD_AUDIO
            value: "false"
          - name: JIGASI_TRANSCRIBER_SEND_TXT
            value: "false"
          - name: JIGASI_TRANSCRIBER_ADVERTISE_URL
            value: "false"
      serviceAccountName: jitsi
---
apiVersion: v1
kind: Service
metadata:
  name: jigasi
  namespace: jitsi
spec:
  type: NodePort
  selector:
    k8s-app: jitsi
    k8s-app-component: jigasi
  ports:
    - name: jigasi-1
      port: 30001
      targetPort: 30001
      nodePort: 30001
    - name: jigasi-2
      port: 30002
      targetPort: 30002
      nodePort: 30002
    - name: jigasi-3
      port: 30003
      targetPort: 30003
      nodePort: 30003
    - name: jigasi-4
      port: 30004
      targetPort: 30004
      nodePort: 30004
    - name: jigasi-5
      port: 30005
      targetPort: 30005
      nodePort: 30005
    - name: jigasi-6
      port: 30006
      targetPort: 30006
      nodePort: 30006
    - name: jigasi-7
      port: 30007
      targetPort: 30007
      nodePort: 30007
    - name: jigasi-8
      port: 30008
      targetPort: 30008
      nodePort: 30008
    - name: jigasi-9
      port: 30009
      targetPort: 30009
      nodePort: 30009
    - name: jigasi-10
      port: 30010
      targetPort: 30010
      nodePort: 30010
    - name: jigasi-11
      port: 30011
      targetPort: 30011
      nodePort: 30011
    - name: jigasi-12
      port: 30012
      targetPort: 30012
      nodePort: 30012
    - name: jigasi-13
      port: 30013
      targetPort: 30013
      nodePort: 30013
    - name: jigasi-14
      port: 30014
      targetPort: 30014
      nodePort: 30014
    - name: jigasi-15
      port: 30015
      targetPort: 30015
      nodePort: 30015
    - name: jigasi-16
      port: 30016
      targetPort: 30016
      nodePort: 30016
    - name: jigasi-17
      port: 30017
      targetPort: 30017
      nodePort: 30017
    - name: jigasi-18
      port: 30018
      targetPort: 30018
      nodePort: 30018
    - name: jigasi-19
      port: 30019
      targetPort: 30019
      nodePort: 30019
    - name: jigasi-20
      port: 30020
      targetPort: 30020
      nodePort: 30020
    - name: jigasi-21
      port: 30021
      targetPort: 30021
      nodePort: 30021
    - name: jigasi-22
      port: 30022
      targetPort: 30022
      nodePort: 30022
    - name: jigasi-23
      port: 30023
      targetPort: 30023
      nodePort: 30023
    - name: jigasi-24
      port: 30024
      targetPort: 30024
      nodePort: 30024
    - name: jigasi-25
      port: 30025
      targetPort: 30025
      nodePort: 30025
    - name: jigasi-26
      port: 30026
      targetPort: 30026
      nodePort: 30026
    - name: jigasi-27
      port: 30027
      targetPort: 30027
      nodePort: 30027
    - name: jigasi-28
      port: 30028
      targetPort: 30028
      nodePort: 30028
    - name: jigasi-29
      port: 30029
      targetPort: 30029
      nodePort: 30029
    - name: jigasi-30
      port: 30030
      targetPort: 30030
      nodePort: 30030
    - name: jigasi-31
      port: 30031
      targetPort: 30031
      nodePort: 30031
    - name: jigasi-32
      port: 30032
      targetPort: 30032
      nodePort: 30032
    - name: jigasi-33
      port: 30033
      targetPort: 30033
      nodePort: 30033
    - name: jigasi-34
      port: 30034
      targetPort: 30034
      nodePort: 30034
    - name: jigasi-35
      port: 30035
      targetPort: 30035
      nodePort: 30035
    - name: jigasi-36
      port: 30036
      targetPort: 30036
      nodePort: 30036
    - name: jigasi-37
      port: 30037
      targetPort: 30037
      nodePort: 30037
    - name: jigasi-38
      port: 30038
      targetPort: 30038
      nodePort: 30038
    - name: jigasi-39
      port: 30039
      targetPort: 30039
      nodePort: 30039
    - name: jigasi-40
      port: 30040
      targetPort: 30040
      nodePort: 30040
    - name: jigasi-41
      port: 30041
      targetPort: 30041
      nodePort: 30041
    - name: jigasi-42
      port: 30042
      targetPort: 30042
      nodePort: 30042
    - name: jigasi-43
      port: 30043
      targetPort: 30043
      nodePort: 30043
    - name: jigasi-44
      port: 30044
      targetPort: 30044
      nodePort: 30044
    - name: jigasi-45
      port: 30045
      targetPort: 30045
      nodePort: 30045
    - name: jigasi-46
      port: 30046
      targetPort: 30046
      nodePort: 30046
    - name: jigasi-47
      port: 30047
      targetPort: 30047
      nodePort: 30047
    - name: jigasi-48
      port: 30048
      targetPort: 30048
      nodePort: 30048
    - name: jigasi-49
      port: 30049
      targetPort: 30049
      nodePort: 30049
    - name: jigasi-50
      port: 30050
      targetPort: 30050
      nodePort: 30050
